import { Deal, DealLog } from '@/types';

export const mockDeals: Deal[] = [
  {
    id: '1',
    productName: 'ABC株式会社',
    proposalMenu: '第一想起取れるくん',
    assignee: '増田 陽',
    referrer: '田中様',
    meetingDate: new Date('2024-01-15'),
    minutes: '初回MTG。現在のマーケティング課題についてヒアリング。競合他社との差別化に悩んでいる状況。',
    summary: 'マーケティング課題のヒアリング。競合差別化がポイント。',
    nextAction: '提案資料作成、競合分析資料準備',
    nextActionDate: new Date('2024-01-22'),
    status: '提案作成中',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    productName: 'XYZ企業',
    proposalMenu: '獲得取れるくん',
    assignee: '渡邊 哲成',
    meetingDate: new Date('2024-01-10'),
    minutes: '2回目MTG。提案内容について詳細検討。予算感についても確認。月額50万円程度での検討を希望。',
    summary: '提案内容詳細検討。予算月額50万円で検討中。',
    nextAction: '正式提案書提出、契約条件詳細化',
    nextActionDate: new Date('2024-01-25'),
    status: '検討中',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    productName: 'PQR商事',
    proposalMenu: 'インハウスキャンプ',
    assignee: '加藤 修慈',
    referrer: '佐藤様',
    meetingDate: new Date('2024-01-08'),
    minutes: '契約締結完了。来月からプロジェクト開始予定。',
    summary: '契約締結完了。来月からプロジェクト開始。',
    nextAction: 'プロジェクト開始準備、キックオフMTG設定',
    nextActionDate: new Date('2024-02-01'),
    status: '成約',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: '4',
    productName: 'LMN株式会社',
    proposalMenu: 'IFキャスティング',
    assignee: '増田 陽',
    meetingDate: new Date('2024-01-12'),
    minutes: 'アポ設定完了。来週初回MTG予定。',
    summary: 'アポ設定完了。来週初回MTG予定。',
    nextAction: '初回MTG実施、ヒアリング準備',
    nextActionDate: new Date('2024-01-19'),
    status: 'アポ設定',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    productName: 'STU技研',
    proposalMenu: '運用コックピット',
    assignee: '渡邊 哲成',
    meetingDate: new Date('2024-01-05'),
    minutes: '検討の結果、今期は見送りとの連絡。来期改めて検討予定。',
    summary: '今期は見送り。来期再検討予定。',
    nextAction: '来期に向けたフォローアップ',
    nextActionDate: new Date('2024-04-01'),
    status: '見送り',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-18'),
  },
];

export const mockDealLogs: DealLog[] = [
  {
    id: 'log1',
    dealId: '1',
    productName: 'ABC株式会社',
    proposalMenu: '第一想起取れるくん',
    assignee: '増田 陽',
    referrer: '田中様',
    meetingDate: new Date('2024-01-15'),
    minutes: '初回MTG。現在のマーケティング課題についてヒアリング。競合他社との差別化に悩んでいる状況。リードジェネレーションの強化を求めている。',
    summary: 'マーケティング課題のヒアリング。競合差別化とリードジェネレーション強化がポイント。',
    nextAction: '提案資料作成、競合分析資料準備',
    nextActionDate: new Date('2024-01-22'),
    status: '提案作成中',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'log2',
    dealId: '2',
    productName: 'XYZ企業',
    proposalMenu: '獲得取れるくん',
    assignee: '渡邊 哲成',
    meetingDate: new Date('2024-01-05'),
    minutes: '初回MTG。事業概要説明とサービス紹介。興味を示してもらえた。',
    summary: '初回MTG完了。サービスに興味あり。',
    nextAction: '詳細提案資料作成',
    nextActionDate: new Date('2024-01-12'),
    status: 'アポ設定',
    createdAt: new Date('2024-01-05'),
  },
  {
    id: 'log3',
    dealId: '2',
    productName: 'XYZ企業',
    proposalMenu: '獲得取れるくん',
    assignee: '渡邊 哲成',
    meetingDate: new Date('2024-01-10'),
    minutes: '2回目MTG。提案内容について詳細検討。予算感についても確認。月額50万円程度での検討を希望。社内稟議のプロセスについても確認。',
    summary: '提案内容詳細検討。予算月額50万円で検討中。社内稟議プロセス確認。',
    nextAction: '正式提案書提出、契約条件詳細化',
    nextActionDate: new Date('2024-01-25'),
    status: '検討中',
    createdAt: new Date('2024-01-10'),
  },
]; 